version: '3.8'

services:
  template-backend-dev:
    image: template-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports: [
      3001:3001
    ]
    volumes:
      - ./backend/:/usr/src/template-backend
    environment: 
      - MONGO_URL=mongodb://the_username:the_password@template-mongo-dev:27017/the_database
    depends_on:
      - template-mongo-dev
    container_name: template-backend-dev
  template-mongo-dev:
    image: mongo
    ports: [
      3456:27017
    ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo_data:/data/db
    container_name: template-mongo-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: [
      8080:80
    ]
    container_name: template-reverse-proxy
    depends_on:
      - template-frontend-dev
      - template-backend-dev
  template-frontend-dev:
    image: template-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports: [
      3000:3000
    ]
    volumes:
      - ./frontend/:/usr/src/template-frontend
    container_name: template-frontend-dev
    tty: true
volumes:
  mongo_data: